export const currentUser = {
  name: 'You',
  handle: 'you',
  initials: 'Y',
  color: '#6366f1',
  bio: 'Đang học React & triển khai app thật 🚀',
  followers: 128,
  following: 97,
}

// Every post AND every reply lives in this one flat list. A top-level post
// has parentId: null; a reply has parentId pointing at whatever it replies
// to — a post or another reply — so threads can nest to any depth.
export const initialItems = [
  {
    id: 1,
    parentId: null,
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    verified: true,
    time: '2h',
    text: 'Vừa deploy xong app đầu tay lên Render 🎉 cảm giác thấy code mình chạy thật ngoài đời khác hẳn so với chạy local.',
    likes: 128,
    reposts: 6,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 101,
    parentId: 1,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '1h',
    text: 'Chúc mừng! Bạn dùng nền tảng nào để build vậy?',
    likes: 5,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 102,
    parentId: 101,
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    verified: true,
    time: '55 phút',
    text: 'Mình dùng Render đó bạn, free tier luôn 😄',
    likes: 8,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 103,
    parentId: 102,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '50 phút',
    text: 'Ngon, để mình thử luôn tối nay.',
    likes: 2,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 104,
    parentId: 1,
    name: 'Thu Trang',
    handle: 'trangthu',
    initials: 'TT',
    color: '#ec4899',
    verified: true,
    time: '40 phút',
    text: 'Nghe hấp dẫn ghê, mình cũng đang định thử.',
    likes: 3,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 2,
    parentId: null,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '4h',
    text: 'Static site vs dynamic site: cái nào cũng có chỗ đứng riêng. Đừng vội gắn database vào mọi thứ khi chưa cần.',
    likes: 342,
    reposts: 22,
    liked: true,
    reposted: false,
    mine: false,
  },
  {
    id: 201,
    parentId: 2,
    name: 'Hoàng Long',
    handle: 'long.builds',
    initials: 'HL',
    color: '#22c55e',
    verified: false,
    time: '2h',
    text: 'Đồng ý, static site nhẹ và dễ maintain hơn nhiều.',
    likes: 12,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 202,
    parentId: 201,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '1h',
    text: 'Chính xác, mình cũng nghĩ vậy.',
    likes: 4,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 3,
    parentId: null,
    name: 'Thu Trang',
    handle: 'trangthu',
    initials: 'TT',
    color: '#ec4899',
    verified: true,
    time: '6h',
    text: 'Hôm nay học được: Vite build ra file tĩnh thì host ở đâu cũng được, không nhất thiết cần server Node chạy 24/7.',
    likes: 89,
    reposts: 3,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 301,
    parentId: 3,
    name: 'Bảo Ngọc',
    handle: 'ngoc.ui',
    initials: 'BN',
    color: '#a855f7',
    verified: false,
    time: '3h',
    text: 'Mình mới biết điều này luôn, cảm ơn bạn!',
    likes: 6,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 4,
    parentId: null,
    name: 'Hoàng Long',
    handle: 'long.builds',
    initials: 'HL',
    color: '#22c55e',
    verified: false,
    time: '9h',
    text: 'Free tier Render bị sleep sau 15 phút không có ai vào — bình thường thôi, đừng hoảng, load lại là lên.',
    likes: 57,
    reposts: 1,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 401,
    parentId: 4,
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    verified: true,
    time: '5h',
    text: 'Ha, lần đầu gặp cũng hoảng thật 😅',
    likes: 9,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
  {
    id: 5,
    parentId: null,
    name: 'Bảo Ngọc',
    handle: 'ngoc.ui',
    initials: 'BN',
    color: '#a855f7',
    verified: false,
    time: '11h',
    text: 'Giao diện đẹp không cần nhiều màu, chỉ cần đúng khoảng cách và đúng font.',
    likes: 210,
    reposts: 12,
    liked: false,
    reposted: true,
    mine: false,
  },
  {
    id: 501,
    parentId: 5,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '6h',
    text: 'Chuẩn luôn, spacing với typography quan trọng hơn màu mè.',
    likes: 7,
    reposts: 0,
    liked: false,
    reposted: false,
    mine: false,
  },
]

// Accounts already followed by default — everyone else starts as "not followed".
export const initialFollowing = ['maianh.codes', 'trangthu', 'ngoc.ui']

export const accounts = initialItems
  .filter((i) => !i.parentId)
  .map(({ name, handle, initials, color, verified }) => ({ name, handle, initials, color, verified }))

export const initialNotifications = [
  {
    id: 1,
    type: 'like',
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    text: 'đã thích bài viết của bạn',
    time: '5 phút',
    read: false,
  },
  {
    id: 2,
    type: 'reply',
    name: 'Thu Trang',
    handle: 'trangthu',
    initials: 'TT',
    color: '#ec4899',
    text: 'đã trả lời: "Ý hay đó!"',
    time: '1 giờ',
    read: false,
  },
  {
    id: 3,
    type: 'follow',
    name: 'Bảo Ngọc',
    handle: 'ngoc.ui',
    initials: 'BN',
    color: '#a855f7',
    text: 'đã bắt đầu theo dõi bạn',
    time: '3 giờ',
    read: true,
  },
  {
    id: 4,
    type: 'repost',
    name: 'Hoàng Long',
    handle: 'long.builds',
    initials: 'HL',
    color: '#22c55e',
    text: 'đã đăng lại bài viết của bạn',
    time: '1 ngày',
    read: true,
  },
  {
    id: 5,
    type: 'like',
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    text: 'đã thích bài viết của bạn',
    time: '2 ngày',
    read: true,
  },
]
