export const currentUser = {
  name: 'You',
  handle: 'you',
  initials: 'Y',
  color: '#6366f1',
}

export const initialPosts = [
  {
    id: 1,
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    verified: true,
    time: '2h',
    text: 'Vừa deploy xong app đầu tay lên Render 🎉 cảm giác thấy code mình chạy thật ngoài đời khác hẳn hẳn so với chạy local.',
    likes: 128,
    replies: 14,
    reposts: 6,
    liked: false,
    reposted: false,
    canFollow: false,
  },
  {
    id: 2,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '4h',
    text: 'Static site vs dynamic site: cái nào cũng có chỗ đứng riêng. Đừng vội gắn database vào mọi thứ khi chưa cần.',
    likes: 342,
    replies: 51,
    reposts: 22,
    liked: true,
    reposted: false,
    canFollow: true,
  },
  {
    id: 3,
    name: 'Thu Trang',
    handle: 'trangthu',
    initials: 'TT',
    color: '#ec4899',
    verified: true,
    time: '6h',
    text: 'Hôm nay học được: Vite build ra file tĩnh thì host ở đâu cũng được, không nhất thiết cần server Node chạy 24/7.',
    likes: 89,
    replies: 9,
    reposts: 3,
    liked: false,
    reposted: false,
    canFollow: false,
  },
  {
    id: 4,
    name: 'Hoàng Long',
    handle: 'long.builds',
    initials: 'HL',
    color: '#22c55e',
    verified: false,
    time: '9h',
    text: 'Free tier Render bị sleep sau 15 phút không có ai vào — bình thường thôi, đừng hoảng, load lại là lên.',
    likes: 57,
    replies: 4,
    reposts: 1,
    liked: false,
    reposted: false,
    canFollow: true,
  },
  {
    id: 5,
    name: 'Bảo Ngọc',
    handle: 'ngoc.ui',
    initials: 'BN',
    color: '#a855f7',
    verified: false,
    time: '11h',
    text: 'Giao diện đẹp không cần nhiều màu, chỉ cần đúng khoảng cách và đúng font.',
    likes: 210,
    replies: 18,
    reposts: 12,
    liked: false,
    reposted: true,
    canFollow: false,
  },
]
