export const currentUser = {
  name: 'You',
  handle: 'you',
  initials: 'Y',
  color: '#6366f1',
  bio: 'Đang học React & triển khai app thật 🚀',
  followers: 128,
  following: 97,
}

export const initialPosts = [
  {
    id: 1,
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    verified: true,
    time: '2h',
    text: 'Vừa deploy xong app đầu tay lên Render 🎉 cảm giác thấy code mình chạy thật ngoài đời khác hẳn so với chạy local.',
    likes: 128,
    replies: 14,
    reposts: 6,
    liked: false,
    reposted: false,
    mine: false,
    repliesList: [
      {
        name: 'Duy Khang',
        handle: 'khang.dev',
        initials: 'DK',
        color: '#0ea5e9',
        text: 'Chúc mừng! Bạn dùng nền tảng nào để build vậy?',
        time: '1h',
      },
      {
        name: 'Thu Trang',
        handle: 'trangthu',
        initials: 'TT',
        color: '#ec4899',
        text: 'Nghe hấp dẫn ghê, mình cũng đang định thử.',
        time: '40 phút',
      },
    ],
  },
  {
    id: 2,
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    verified: false,
    time: '4h',
    text: 'Static site vs dynamic site: cái nào cũng có chỗ đứng riêng. Đừng vội gắn database vào mọi thứ khi chưa cần.',
    likes: 342,
    replies: 51,
    reposts: 22,
    liked: true,
    reposted: false,
    mine: false,
    repliesList: [
      {
        name: 'Hoàng Long',
        handle: 'long.builds',
        initials: 'HL',
        color: '#22c55e',
        text: 'Đồng ý, static site nhẹ và dễ maintain hơn nhiều.',
        time: '2h',
      },
    ],
  },
  {
    id: 3,
    name: 'Thu Trang',
    handle: 'trangthu',
    initials: 'TT',
    color: '#ec4899',
    verified: true,
    time: '6h',
    text: 'Hôm nay học được: Vite build ra file tĩnh thì host ở đâu cũng được, không nhất thiết cần server Node chạy 24/7.',
    likes: 89,
    replies: 9,
    reposts: 3,
    liked: false,
    reposted: false,
    mine: false,
    repliesList: [
      {
        name: 'Bảo Ngọc',
        handle: 'ngoc.ui',
        initials: 'BN',
        color: '#a855f7',
        text: 'Mình mới biết điều này luôn, cảm ơn bạn!',
        time: '3h',
      },
    ],
  },
  {
    id: 4,
    name: 'Hoàng Long',
    handle: 'long.builds',
    initials: 'HL',
    color: '#22c55e',
    verified: false,
    time: '9h',
    text: 'Free tier Render bị sleep sau 15 phút không có ai vào — bình thường thôi, đừng hoảng, load lại là lên.',
    likes: 57,
    replies: 4,
    reposts: 1,
    liked: false,
    reposted: false,
    mine: false,
    repliesList: [
      {
        name: 'Mai Anh',
        handle: 'maianh.codes',
        initials: 'MA',
        color: '#f97316',
        text: 'Ha, lần đầu gặp cũng hoảng thật 😅',
        time: '5h',
      },
    ],
  },
  {
    id: 5,
    name: 'Bảo Ngọc',
    handle: 'ngoc.ui',
    initials: 'BN',
    color: '#a855f7',
    verified: false,
    time: '11h',
    text: 'Giao diện đẹp không cần nhiều màu, chỉ cần đúng khoảng cách và đúng font.',
    likes: 210,
    replies: 18,
    reposts: 12,
    liked: false,
    reposted: true,
    mine: false,
    repliesList: [
      {
        name: 'Duy Khang',
        handle: 'khang.dev',
        initials: 'DK',
        color: '#0ea5e9',
        text: 'Chuẩn luôn, spacing với typography quan trọng hơn màu mè.',
        time: '6h',
      },
    ],
  },
]

// Accounts already followed by default — everyone else starts as "not followed".
export const initialFollowing = ['maianh.codes', 'trangthu', 'ngoc.ui']

export const accounts = initialPosts.map(({ name, handle, initials, color, verified }) => ({
  name,
  handle,
  initials,
  color,
  verified,
}))

export const initialNotifications = [
  {
    id: 1,
    type: 'like',
    name: 'Duy Khang',
    handle: 'khang.dev',
    initials: 'DK',
    color: '#0ea5e9',
    text: 'đã thích bài viết của bạn',
    time: '5 phút',
    read: false,
  },
  {
    id: 2,
    type: 'reply',
    name: 'Thu Trang',
    handle: 'trangthu',
    initials: 'TT',
    color: '#ec4899',
    text: 'đã trả lời: "Ý hay đó!"',
    time: '1 giờ',
    read: false,
  },
  {
    id: 3,
    type: 'follow',
    name: 'Bảo Ngọc',
    handle: 'ngoc.ui',
    initials: 'BN',
    color: '#a855f7',
    text: 'đã bắt đầu theo dõi bạn',
    time: '3 giờ',
    read: true,
  },
  {
    id: 4,
    type: 'repost',
    name: 'Hoàng Long',
    handle: 'long.builds',
    initials: 'HL',
    color: '#22c55e',
    text: 'đã đăng lại bài viết của bạn',
    time: '1 ngày',
    read: true,
  },
  {
    id: 5,
    type: 'like',
    name: 'Mai Anh',
    handle: 'maianh.codes',
    initials: 'MA',
    color: '#f97316',
    text: 'đã thích bài viết của bạn',
    time: '2 ngày',
    read: true,
  },
]
